### ISSUE TITLE
Shared CSS Properties

### ISSUE THREAD

**Issue by cyouh95** [theezwright/prj-rev-bwfs-dasmoto#3]
For properties shared among multiple elements, you could specify them all at once using comma separated selectors, instead of having to write it multiple times for each:

```css
h1, h2, .price {
  font-family: Helvetica;
  font-weight: bold;
  ...
}
```

https://github.com/theezwright/prj-rev-bwfs-dasmoto/blob/master/Dasmotos/resources/css/style.css
